apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kubeacademy
  name: building-apps-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubeacademy
  template:
    metadata:
      labels:
        app: kubeacademy
    spec:
      containers:
      - name: building-apps-container
        image: lruihan/building-apps:0.1
