apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: ambassador-container
    image: haproxy:lts
    volumeMounts:
    - name: foo
      mountPath: "/usr/local/etc/haproxy/"
      readOnly: true
  volumes:
  - name: foo
    configMap:
      name: haproxy-config
