apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-1
  namespace: test

spec:
  schedule: "5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: perl
            image: perl:5
            imagePullPolicy: IfNotPresent
            command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
          restartPolicy: Never
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 2
  startingDeadlineSeconds: 17

# Switch namespace: kubectl config set-context --current --namespace=test
# pods=$(kubectl get pods --selector=job-name=cronjob-1-27794225 --output=jsonpath={.items[*].metadata.name})
# kubectl logs $pods
# kubectl -n test create job --from=cronjob/cronjob-1 cron-test
# kubectl get jobs --watch
# kubectl create cronjob -h
# kubectl explain cronjob.spec