apiVersion: apps/v1
kind: Deployment
metadata:
  name:  deployment-xyz
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: logger-dev
        image: lfccncf/busybox:1
      - name: adapter-zen
        image: lfccncf/fluentd:v0.12
