apiVersion: skaffold/v2beta24
kind: Config
metadata:
  name: my-app
build:
  artifacts:
  - image: lruihan/building-apps
    context: src
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
    - k8s/service.yaml
