apiVersion: v1
{{- if .Values.persistence.enabled }}
kind: PersistentVolumeClaim
metadata:
  name: {{ include "minio.fullname" . }}
  labels:
    {{- include "minio.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.persistence.size | quote }}
{{- end }}
